kind: pipeline
type: docker
name: deploy-server

platform:
  os: linux
  arсh: amd64

steps:
  - name: send
    image: plugins/webhook
    settings:
      urls:
        -
          from_secret: SERVER_PWD
    when: # 无论成功失败都运行
      status:
        - failure
        - success

trigger:
  branch:
  - main